/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movie_database;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author calpo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        BtnInsertMenu = new javax.swing.JButton();
        BtnUpdateMenu = new javax.swing.JButton();
        BtnSearchMenu = new javax.swing.JButton();
        BtnDeleteMenu = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle.setText("Select one of the option buttons below:");
        lblTitle.setName(""); // NOI18N

        lblTitle1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        lblTitle1.setText("Movie Database Application");
        lblTitle1.setName(""); // NOI18N

        BtnInsertMenu.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnInsertMenu.setText("Insert Movie");
        BtnInsertMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertMenuActionPerformed(evt);
            }
        });

        BtnUpdateMenu.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnUpdateMenu.setText("Update Movie");
        BtnUpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateMenuActionPerformed(evt);
            }
        });

        BtnSearchMenu.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnSearchMenu.setText("Search/Show Movies");
        BtnSearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchMenuActionPerformed(evt);
            }
        });

        BtnDeleteMenu.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnDeleteMenu.setText("Delete Movie");
        BtnDeleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteMenuActionPerformed(evt);
            }
        });

        BtnClose.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnClose.setText("Exit Application");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnInsertMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnUpdateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDeleteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInsertMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDeleteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        // close application
        System.exit(0);
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void BtnInsertMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertMenuActionPerformed
        // open Insert form
        InsertMovie addMovie = new InsertMovie();
        addMovie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnInsertMenuActionPerformed

    private void BtnUpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateMenuActionPerformed
        // open update form
        UpdateMovie updateMovie = new UpdateMovie();
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        //populate cbo
        final String retrieveQuery = "SELECT id from movie";
        mc.setQuery(retrieveQuery);
        mc.runQuery();
        ResultSet output = mc.getResultSet();
        try
        { 
            while((output != null) && (output.next()))
            { 
                int movieID;
                movieID = output.getInt(1);
                //add items to id combobox
                String id = Integer.toString(movieID);
                updateMovie.cboID.addItem(output.getString(1));
                } 
            } 
        catch (SQLException sqle)
        { 
            System.out.println("Exception when printing all students: " + sqle.toString());
        }
        mc.closeConnection();
        updateMovie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnUpdateMenuActionPerformed

    private void BtnSearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchMenuActionPerformed
        // open search form
        SearchMovies searchMovie = new SearchMovies();
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        final String retrieveQuery = "SELECT id from movie";
        mc.setQuery(retrieveQuery);
        mc.runQuery();
        ResultSet output = mc.getResultSet();
        try
        { 
            while((output != null) && (output.next()))
            { 
                int movieID;
                movieID = output.getInt(1);
                //add items to id combobox
                String id = Integer.toString(movieID);
                searchMovie.cboID.addItem(output.getString(1));
                } 
            } 
        catch (SQLException sqle)
        { 
            System.out.println("Exception when printing all students: " + sqle.toString());
        }
        mc.closeConnection();
        searchMovie.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_BtnSearchMenuActionPerformed

    private void BtnDeleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteMenuActionPerformed
        // open delete form
        DeleteMovie deleteMovie = new DeleteMovie();
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        //populate cbo
        final String retrieveQuery = "SELECT id from movie";
        mc.setQuery(retrieveQuery);
        mc.runQuery();
        ResultSet output = mc.getResultSet();
        try
        { 
            while((output != null) && (output.next()))
            { 
                int movieID;
                movieID = output.getInt(1);
                //add items to id combobox
                String id = Integer.toString(movieID);
                deleteMovie.cboID.addItem(output.getString(1));
                } 
            } 
        catch (SQLException sqle)
        { 
            System.out.println("Exception when printing all students: " + sqle.toString());
        }
        mc.closeConnection();
        deleteMovie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnDeleteMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnDeleteMenu;
    private javax.swing.JButton BtnInsertMenu;
    private javax.swing.JButton BtnSearchMenu;
    private javax.swing.JButton BtnUpdateMenu;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
