/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movie_database;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.PreparedStatement;

/**
 *
 * @author calpo
 */
public class SearchMovies extends javax.swing.JFrame {

    /**
     * Creates new form SearchMovies
     */
    public SearchMovies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        cboID = new javax.swing.JComboBox();
        lblTitle2 = new javax.swing.JLabel();
        BtnSearch = new javax.swing.JButton();
        BtnShow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        BtnMenu = new javax.swing.JButton();
        BtnClearSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        lblTitle1.setText("Search for a Movie");
        lblTitle1.setName(""); // NOI18N

        lblTitle.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle.setText("Choose ID of the movie you would like to view");
        lblTitle.setName(""); // NOI18N

        lblTitle2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle2.setText("Movie ID:");
        lblTitle2.setName(""); // NOI18N

        BtnSearch.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnSearch.setText("Search by ID");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        BtnShow.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnShow.setText("Show All Movies");
        BtnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShowActionPerformed(evt);
            }
        });

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        BtnMenu.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnMenu.setText("Return to Menu");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        BtnClearSearch.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnClearSearch.setText("Clear Results");
        BtnClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTitle2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboID, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblTitle1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnSearch)
                        .addGap(176, 176, 176)
                        .addComponent(BtnShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(BtnClearSearch)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnMenu)
                .addGap(289, 289, 289))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        // TODO add your handling code here:
        MainFrame m = new MainFrame();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void BtnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShowActionPerformed
        // TODO add your handling code here:
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        //clear txtbox
        txtOutput.setText("");
        try
        {
            final String retrieveQuery = "SELECT * FROM movie";
            mc.setQuery(retrieveQuery);
            mc.runQuery();
            ResultSet output = mc.getResultSet();
            //Read and display movie info
            if (null != output)
            {
                while(output.next())
                {
                    txtOutput.append("\n" + output.getInt("id"));
                    txtOutput.append(", " + output.getString("title"));
                    txtOutput.append(", " + output.getDate("release_date"));
                }
            }
        }
        catch(SQLException error)
        {
            System.err.println("Error reading records");
        }
    }//GEN-LAST:event_BtnShowActionPerformed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        //print movie details based on selected Id
        String mid = (String)cboID.getSelectedItem();
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        getMovieDataGivenID(mid);
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void BtnClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearSearchActionPerformed
        // clear textbox
        txtOutput.setText("");
    }//GEN-LAST:event_BtnClearSearchActionPerformed

     /**
     * Find a movie with a given ID
     * @return ResultSet containing movie with the specified ID
     */
     public String[] getMovieDataGivenID(final String movieID) {
        String[] data = new String[3];
        ResultSet movieRS = null;
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        final String getQuery = "SELECT * FROM movie WHERE id = ?";
        //clear txtbox
        txtOutput.setText("");
        try  {
            PreparedStatement pstmt = mc.getConnection().prepareStatement(getQuery);
            pstmt.setString(1, movieID);
            movieRS = pstmt.executeQuery();
        }  catch (SQLException sqle) {
            System.out.println("Exception when  getting movie data: " + sqle.toString());
        }

        try {
            while ((null != movieRS) && (movieRS.next())) {
                String id = movieRS.getString(1);
                int budget = movieRS.getInt(2);
                String homepage = movieRS.getString(3);
                String original_language = movieRS.getString(4);
                String original_title = movieRS.getString(5);
                String overview = movieRS.getString(6);
                float popularity = movieRS.getFloat(7);
                Date release_date = movieRS.getDate(8);
                int revenue = movieRS.getInt(9);
                int runtime = movieRS.getInt(10);
                String release_status = movieRS.getString(11);
                String tagline = movieRS.getString(12);
                String title = movieRS.getString(13);
                float vote_average = movieRS.getFloat(14);
                int vote_count = movieRS.getInt(15);
                txtOutput.append("\n" + movieRS.getInt("id"));
                txtOutput.append("\n" + movieRS.getInt("budget"));
                txtOutput.append("\n" + movieRS.getString("homepage"));
                txtOutput.append("\n" + movieRS.getString("original_language"));
                txtOutput.append("\n" + movieRS.getString("original_title"));
                txtOutput.append("\n" + movieRS.getString("overview"));
                txtOutput.append("\n" + movieRS.getFloat("popularity"));
                txtOutput.append("\n" + movieRS.getDate("release_date"));
                txtOutput.append("\n" + movieRS.getInt("revenue"));
                txtOutput.append("\n" + movieRS.getInt("runtime"));
                txtOutput.append("\n" + movieRS.getString("release_status"));
                txtOutput.append("\n" + movieRS.getString("tagline"));
                txtOutput.append("\n" + movieRS.getString("title"));
                txtOutput.append("\n" + movieRS.getFloat("vote_average"));
                txtOutput.append("\n" + movieRS.getInt("vote_count"));
            }
        } catch (SQLException sqle) {
            System.out.println("Error finding movie: " + sqle.toString());
        }
        return data;
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClearSearch;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JButton BtnShow;
    public javax.swing.JComboBox cboID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
