/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movie_database;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author calpo
 */
public class UpdateMovie extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMovie
     */
    public UpdateMovie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        lblTitle4 = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        lblTitle6 = new javax.swing.JLabel();
        lblTitle7 = new javax.swing.JLabel();
        lblTitle8 = new javax.swing.JLabel();
        lblTitle9 = new javax.swing.JLabel();
        lblTitle10 = new javax.swing.JLabel();
        lblTitle11 = new javax.swing.JLabel();
        lblTitle12 = new javax.swing.JLabel();
        lblTitle13 = new javax.swing.JLabel();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle15 = new javax.swing.JLabel();
        lblTitle16 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        TxtBudget = new javax.swing.JTextField();
        TxtHomepage = new javax.swing.JTextField();
        TxtOrigLan = new javax.swing.JTextField();
        TxtOrigTitle = new javax.swing.JTextField();
        TxtPopularity = new javax.swing.JTextField();
        TxtDate = new javax.swing.JTextField();
        TxtRevenue = new javax.swing.JTextField();
        TxtRuntime = new javax.swing.JTextField();
        TxtStatus = new javax.swing.JTextField();
        TxtTagline = new javax.swing.JTextField();
        TxtTitle = new javax.swing.JTextField();
        TxtAverage = new javax.swing.JTextField();
        TxtCount = new javax.swing.JTextField();
        BtnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtOverview = new javax.swing.JTextArea();
        BtnMenu = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        cboID = new javax.swing.JComboBox();
        lblTitle17 = new javax.swing.JLabel();
        BtnUpdateSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        lblTitle1.setText("Update Movie");
        lblTitle1.setName(""); // NOI18N

        lblTitle2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle2.setText("ID:");
        lblTitle2.setName(""); // NOI18N

        lblTitle3.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle3.setText("Budget:");
        lblTitle3.setName(""); // NOI18N

        lblTitle4.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle4.setText("Homepage:");
        lblTitle4.setName(""); // NOI18N

        lblTitle5.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle5.setText("Original Language:");
        lblTitle5.setName(""); // NOI18N

        lblTitle6.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle6.setText("Original Title:");
        lblTitle6.setName(""); // NOI18N

        lblTitle7.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle7.setText("Overview:");
        lblTitle7.setName(""); // NOI18N

        lblTitle8.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle8.setText("Popularity:");
        lblTitle8.setName(""); // NOI18N

        lblTitle9.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle9.setText("Release Date:");
        lblTitle9.setName(""); // NOI18N

        lblTitle10.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle10.setText("Revenue:");
        lblTitle10.setName(""); // NOI18N

        lblTitle11.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle11.setText("Runtime:");
        lblTitle11.setName(""); // NOI18N

        lblTitle12.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle12.setText("Release Status:");
        lblTitle12.setName(""); // NOI18N

        lblTitle13.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle13.setText("Tagline:");
        lblTitle13.setName(""); // NOI18N

        lblTitle14.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle14.setText("Title:");
        lblTitle14.setName(""); // NOI18N

        lblTitle15.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle15.setText("Vote Average:");
        lblTitle15.setName(""); // NOI18N

        lblTitle16.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle16.setText("Vote Count:");
        lblTitle16.setName(""); // NOI18N

        TxtID.setEditable(false);

        TxtPopularity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPopularityActionPerformed(evt);
            }
        });

        TxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDateActionPerformed(evt);
            }
        });

        BtnUpdate.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnUpdate.setText("Update Movie");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        TxtOverview.setColumns(20);
        TxtOverview.setRows(5);
        jScrollPane1.setViewportView(TxtOverview);

        BtnMenu.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnMenu.setText("Return to menu");
        BtnMenu.setActionCommand("Return to Menu");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        BtnClear.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle2)
                    .addComponent(lblTitle3)
                    .addComponent(lblTitle4)
                    .addComponent(lblTitle7)
                    .addComponent(lblTitle6)
                    .addComponent(lblTitle5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtBudget, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtHomepage, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle14)
                            .addComponent(lblTitle13)
                            .addComponent(lblTitle12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtOrigTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtOrigLan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle15)
                            .addComponent(lblTitle16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TxtTagline)
                    .addComponent(TxtTitle)
                    .addComponent(TxtAverage)
                    .addComponent(TxtCount))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle8)
                    .addComponent(lblTitle9)
                    .addComponent(lblTitle10)
                    .addComponent(lblTitle11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtPopularity, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtDate)
                            .addComponent(TxtRevenue)
                            .addComponent(TxtRuntime))
                        .addGap(120, 412, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(BtnMenu)
                        .addGap(95, 95, 95))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle2)
                    .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle12)
                    .addComponent(TxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle3)
                    .addComponent(TxtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle13)
                    .addComponent(TxtTagline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle4)
                    .addComponent(TxtHomepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle14)
                    .addComponent(TxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle5)
                        .addComponent(TxtOrigLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtAverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle6)
                    .addComponent(TxtOrigTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle16)
                    .addComponent(TxtCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle8)
                    .addComponent(TxtPopularity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle9)
                    .addComponent(TxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle10)
                    .addComponent(TxtRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle11)
                    .addComponent(TxtRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        lblTitle.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle.setText("Choose ID of the movie you would like to update:");
        lblTitle.setName(""); // NOI18N

        lblTitle17.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTitle17.setText("Movie ID:");
        lblTitle17.setName(""); // NOI18N

        BtnUpdateSearch.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BtnUpdateSearch.setText("Search");
        BtnUpdateSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle1)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(BtnUpdateSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(222, 222, 222))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle17)
                    .addComponent(BtnUpdateSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPopularityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPopularityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPopularityActionPerformed

    private void TxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDateActionPerformed

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        // TODO add your handling code here:
        MainFrame m = new MainFrame();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void BtnUpdateSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateSearchActionPerformed
        // call id function
        String mid = (String)cboID.getSelectedItem();
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        getMovieDataGivenID(mid);
    }//GEN-LAST:event_BtnUpdateSearchActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        //clear txtboxes
        TxtID.setText("");
        TxtBudget.setText("");
        TxtHomepage.setText("");
        TxtOrigLan.setText("");
        TxtOrigTitle.setText("");
        TxtOverview.setText("");
        TxtPopularity.setText("");
        TxtDate.setText("");
        TxtRevenue.setText("");
        TxtRuntime.setText("");
        TxtStatus.setText("");
        TxtTagline.setText("");
        TxtTitle.setText("");
        TxtAverage.setText("");
        TxtCount.setText("");
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        //update record
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        //valiadtion to see if text has been entered
        int id = Integer.parseInt(TxtID.getText());
        int budget= Integer.parseInt(TxtBudget.getText());
        String homepage = TxtHomepage.getText();
        String origLan = TxtOrigLan.getText();
        String origTitle = TxtOrigTitle.getText();
        String overview = TxtOverview.getText();
        float popularity = Float.parseFloat(TxtPopularity.getText());
        Date release_date = Date.valueOf(TxtDate.getText());
        int revenue = Integer.parseInt(TxtRevenue.getText());
        int runtime = Integer.parseInt(TxtRuntime.getText());
        String status = TxtStatus.getText();
        String tagline = TxtTagline.getText();
        String title = TxtTitle.getText();
        float average = Float.parseFloat(TxtAverage.getText());
        int count = Integer.parseInt(TxtCount.getText());
        //blank input validation
        if (homepage.isEmpty()||origLan.isEmpty()||origTitle.isEmpty()||overview.isEmpty()){
            JOptionPane.showMessageDialog(null, "Field missing, please enter");
        } else{
            id = Integer.parseInt(TxtID.getText());
            budget= Integer.parseInt(TxtBudget.getText());
            homepage = TxtHomepage.getText();
            origLan = TxtOrigLan.getText();
            origTitle = TxtOrigTitle.getText();
            overview = TxtOverview.getText();
            popularity = Float.parseFloat(TxtPopularity.getText());
            release_date = Date.valueOf(TxtDate.getText());
            revenue = Integer.parseInt(TxtRevenue.getText());
            runtime = Integer.parseInt(TxtRuntime.getText());
            status = TxtStatus.getText();
            tagline = TxtTagline.getText();
            title = TxtTitle.getText();
            average = Float.parseFloat(TxtAverage.getText());
            count = Integer.parseInt(TxtCount.getText()); 
            mc.updateMovie(id, budget, homepage, origLan, origTitle, overview, popularity, release_date, revenue, runtime, status, tagline, title, average, count);
            mc.closeConnection();
            JOptionPane.showMessageDialog(null, "Record updated");
    }//GEN-LAST:event_BtnUpdateActionPerformed
    }
    /**
     * Find a movie with a given ID
     * @return ResultSet containing movie with the specified ID
     */
     public String[] getMovieDataGivenID(final String movieID) {
        String[] data = new String[3];
        ResultSet movieRS = null;
        MovieDBConnect mc = new MovieDBConnect("movie_db");
        final String getQuery = "SELECT * FROM movie WHERE id = ?";
        try  {
            PreparedStatement pstmt = mc.getConnection().prepareStatement(getQuery);
            pstmt.setString(1, movieID);
            movieRS = pstmt.executeQuery();
        }  catch (SQLException sqle) {
            System.out.println("Exception when  getting movie data: " + sqle.toString());
        }

        try {
            while ((null != movieRS) && (movieRS.next())) {
                String id = movieRS.getString(1);
                int budget = movieRS.getInt(2);
                String homepage = movieRS.getString(3);
                String original_language = movieRS.getString(4);
                String original_title = movieRS.getString(5);
                String overview = movieRS.getString(6);
                float popularity = movieRS.getFloat(7);
                Date release_date = movieRS.getDate(8);
                int revenue = movieRS.getInt(9);
                int runtime = movieRS.getInt(10);
                String release_status = movieRS.getString(11);
                String tagline = movieRS.getString(12);
                String title = movieRS.getString(13);
                float vote_average = movieRS.getFloat(14);
                int vote_count = movieRS.getInt(15);
                TxtID.setText(String.valueOf(movieRS.getInt("id")));
                TxtBudget.setText(String.valueOf(movieRS.getInt("budget")));
                TxtHomepage.setText(movieRS.getString("homepage"));
                TxtOrigLan.setText(movieRS.getString("original_language"));
                TxtOrigTitle.setText(movieRS.getString("original_title"));
                TxtOverview.setText(movieRS.getString("overview"));
                TxtPopularity.setText(String.valueOf(movieRS.getFloat("popularity")));
                TxtDate.setText(String.valueOf(movieRS.getDate("release_date")));
                TxtRevenue.setText(String.valueOf(movieRS.getInt("revenue")));
                TxtRuntime.setText(String.valueOf(movieRS.getInt("runtime")));
                TxtStatus.setText(movieRS.getString("release_status"));
                TxtTagline.setText(movieRS.getString("tagline"));
                TxtTitle.setText(movieRS.getString("title"));
                TxtAverage.setText(String.valueOf(movieRS.getFloat("vote_average")));
                TxtCount.setText(String.valueOf(movieRS.getInt("vote_count")));
            }
        } catch (SQLException sqle) {
            System.out.println("Error finding movie: " + sqle.toString());
        }
        return data;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton BtnUpdateSearch;
    private javax.swing.JTextField TxtAverage;
    private javax.swing.JTextField TxtBudget;
    private javax.swing.JTextField TxtCount;
    private javax.swing.JTextField TxtDate;
    private javax.swing.JTextField TxtHomepage;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtOrigLan;
    private javax.swing.JTextField TxtOrigTitle;
    private javax.swing.JTextArea TxtOverview;
    private javax.swing.JTextField TxtPopularity;
    private javax.swing.JTextField TxtRevenue;
    private javax.swing.JTextField TxtRuntime;
    private javax.swing.JTextField TxtStatus;
    private javax.swing.JTextField TxtTagline;
    private javax.swing.JTextField TxtTitle;
    public javax.swing.JComboBox cboID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle10;
    private javax.swing.JLabel lblTitle11;
    private javax.swing.JLabel lblTitle12;
    private javax.swing.JLabel lblTitle13;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle16;
    private javax.swing.JLabel lblTitle17;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    // End of variables declaration//GEN-END:variables
}
